#!/usr/bin/env python
import sys
import wallaroo.experimental
import asyncio
from nats.aio.client import Client as NATS

connector = wallaroo.experimental.SourceConnector(required_params=['subject'])
connector.connect()

async def main():
    print("started")
    ncon = NATS() 
    loop = asyncio.get_running_loop()   
    await ncon.connect("nats://127.0.0.1:4222", loop=loop)
    print("Connected to NATS")
    async def fun(msg):
        connector.write(msg.data)
    await ncon.subscribe(connector.params.subject, cb=fun)
    while True:
        await asyncio.sleep(1)

asyncio.run(main())

