#!/usr/bin/env python
import sys
import wallaroo.experimental
import asyncio
from nats.aio.client import Client as NATS
from aioify import aioify

connector = wallaroo.experimental.SinkConnector(required_params=['subject'])
connector.listen()

async def main():
    ncon = NATS()    
    loop = asyncio.get_running_loop()
    await ncon.connect("nats://127.0.0.1:4222", loop=loop)
    print("Connected to NATS")
    aiocon = aioify(obj=connector,name="aiocon")
    while True:
        msg = await aiocon.read()
        print(msg)
        await ncon.publish(connector.params.subject,msg)

asyncio.run(main())